ARG ROS_DISTRO=humble
FROM nvcr.io/nvidia/isaac/ros:aarch64-ros2_humble-isaac_ros_dev

RUN apt-get update && apt-get install -y \
    build-essential cmake ninja-build ccache gdb \
    libeigen3-dev libopencv-dev libpcl-dev \
    python3-pip python3-colcon-common-extensions \
    git vim tmux wget \
    && rm -rf /var/lib/apt/lists/*

# Install MAVROS and Python dependencies based on VSLAM-UAV example
RUN apt-get update && apt-get install -y \
    python3-vcstool \
    python3-rosinstall-generator \
    python3-osrf-pycommon \
    ros-humble-tf-transformations \
    ros-humble-mavros \
    ros-humble-mavros-msgs \
    && rm -rf /var/lib/apt/lists/*

# Install OAK-D / DepthAI dependencies
RUN apt-get update && apt-get install -y \
    ros-humble-depthai-ros \
    libusb-1.0-0-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install -U empy==3.3.4 pyros-genmsg setuptools packaging pymavlink transforms3d

# Install geographiclib datasets (MAVROS dependency)
RUN wget https://raw.githubusercontent.com/mavlink/mavros/ros2/mavros/scripts/install_geographiclib_datasets.sh && \
    chmod +x install_geographiclib_datasets.sh && \
    ./install_geographiclib_datasets.sh && \
    rm install_geographiclib_datasets.sh

# Clone external components (mavrospy, motion_capture_tracking)
WORKDIR /ros2_ws/src
RUN git clone -b ros2 https://github.com/bandofpv/mavrospy.git && \
    git clone --recurse-submodules https://github.com/IMRCLab/motion_capture_tracking.git

ENV CCACHE_DIR=/ccache
ENV FCU_URL=/dev/ttyUSB0:921600
ENV ROS_DOMAIN_ID=1

WORKDIR /ros2_ws/src/drone_autonomy_platform
CMD ["/bin/bash"]
